name: LeetCode Reminder
on:
  schedule:
    - cron: "30 4 * * *"    # 10:00 AM IST
    - cron: "30 6 * * *"    # 12:00 PM IST
    - cron: "30 16 * * *"   # 10:00 PM IST
  workflow_dispatch:         # For manual triggers

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: node index.js
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}